# Generated by Django 4.1.3 on 2022-12-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_listing_brand_listing_color_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='color',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='listing',
            name='engine',
            field=models.CharField(default='', max_length=24),
        ),
        migrations.AlterField(
            model_name='listing',
            name='model',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vin',
            field=models.CharField(default='', max_length=17),
        ),
    ]
